### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by foscomputerservices** [PureSwift/Predicate#2]
I've been playing around with this library for the past few hours trying to understand how it supports Linux.  It appears that it delegates calls to NSExpression.

While it's true that [NSExpression](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSExpression.swift) is available as a type on Linux, every call returns NSUnimplemented.

Additionally #keypath is unsupported by the Linux swift compiler.

I reworked all of the tests and code a bit to get them to compile on Linux, but, as expected, when you run them you get:  

> Fatal error: init(forConstantValue:) is not yet implemented: file Foundation/NSExpression.swift, line 56

Am I missing something?  Thanks!

**Comment by colemancda** [comment]
This library supports Linux and runs unit tests on Linux in the CI.
